Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;

namespace Torus_Tile.Controllers
{
    public class AuthController : Controller
    {


        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(string user_id, string user_pw, string user_pw2)
        {
            return View();
        }


        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(string user_id, string user_pw)
        {
            try
            {
                var con = this.CreateConnection();
                string cmdText = $"select * from users where userid = '{user_id}' and userpw = '{user_pw}';";
                MySqlCommand cmd = new MySqlCommand(cmdText, con);
                var result = cmd.ExecuteReader();

                if (result.HasRows)
                {

                    while (result.Read())
                    {  
                        HttpContext.Session.SetString("user", result["userid"].ToString());
                    }

                    ViewData["error"] = true;
                    ViewData["loginSuccessful"] = true;
                    ViewData["userNotFound"] = false;
                    return Redirect("/home/index");

                }
                else
                {
                    ViewData["error"] = false;
                    ViewData["loginSuccessful"] = false;
                    ViewData["userNotFound"] = true;
                    return View();
                }
            }
            catch
            {
                ViewData["error"] = true;
                ViewData["loginSuccessful"] = false;
                ViewData["userNotFound"] = false;
                return View();
            }

        }


        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return Redirect("/auth/login");
        }


        public MySqlConnection CreateConnection()
        {
            MySqlConnectionStringBuilder strConn = new MySqlConnectionStringBuilder();
            strConn.Server = "localhost";
            strConn.Port = 3306;
            strConn.UserID = "root";
            strConn.Password = "Delkaiser920!";
            strConn.Database = "torustile";

            //string strConn = "server=127.0.0.1;database=onlineshopwebsite;user=root;password=Delkaiser920!;port=3306;";

            MySqlConnection conn = new MySqlConnection(strConn.ToString());
            conn.Open();

            return conn;
        } // <-- Opens mysql server and return. Easy to use.

    }
}

Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using Torus_Tile.Models;

namespace Torus_Tile.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult FloorTiles()
        {
            TileShop ts = new TileShop();
            ViewData["tile products"] = ts.getTileProductsList();
            return View();
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public RedirectResult Add(string code, string name, double price, double price_sqf, IFormFile pd_Image)
        {
            string pictureUrl = null;

            if(pd_Image.Length > 0)
            {

                // -- Get the image and save it to the server.
                var fileName = Path.GetFileName(pd_Image.FileName);
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot/images", fileName);
                var stream = new FileStream(filePath, FileMode.Create);
                pd_Image.CopyTo(stream);
                pictureUrl = "/images/" + fileName;
            }


            TileShop ts = new TileShop();


            ts.add_TileProduct(code, name, price, price_sqf, pictureUrl);
            ViewData["tile products"] = ts.getTileProductsList();
            
            return Redirect("/Product/FloorTiles");
        }


        public MySqlConnection connServer()
        {
            MySqlConnectionStringBuilder strConn = new MySqlConnectionStringBuilder();
            strConn.Server = "localhost";
            strConn.Port = 3306;
            strConn.UserID = "root";
            strConn.Password = "Delkaiser920!";
            strConn.Database = "torustile";

            //string strConn = "server=127.0.0.1;database=onlineshopwebsite;user=root;password=Delkaiser920!;port=3306;";

            MySqlConnection conn = new MySqlConnection(strConn.ToString());
            conn.Open();

            return conn;
        } // <-- Opens mysql server and return. Easy to use.


        public string Encrypt_imgDirectory()
        {
            return "";
        }

        public string Encrypt_imgName()
        {
            return "";
        }

    }
}

Views/Shared/_Layout.cshtml
@{
    @using Microsoft.AspNetCore.Http;
    @inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor


    var user = (string)HttpContextAccessor.HttpContext.Session.GetString("user");

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Torus Tile</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Torus Tile</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <div class="dropdown">
                            <li class="nav-item">
                                <a class="nav-link" href="" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Products
                                </a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="FloorTiles">Floor tiles</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Products">Wall & Mosaic tiles</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Products">Tools</a>
                                </div>
                            </li>

                        </div>


                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>

                        @{
                            if (user == null)
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                                </li>
                            }
                            else
                            { 
                                <li class="nav-item">
                                    <a class="nav-link">Welcome, @(user).</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                                </li>
                                
                            }

                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Torus Tile - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>